version: "3.5"
services:
  src:
    build:
      context: src/
    volumes:
      - ./src:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    links:
      - api
      - mongo
    depends_on:
      - api

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: usersdb
    volumes:
      - /home/mongodb/database:/data/db
    logging:
      driver: none
    ports:
      - "27017:27017"

  api:
    build:
      context: api/
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "8000:8000"

    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_DB=commando
    #   - POSTGRES_PASSWORD=example
